{{- if .Values.allowAllIssuerRbac -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "cert-manager-approver-policy.labels" . | nindent 4 }}
  name: {{ include "cert-manager-approver-policy.name" . }}-allow-all
rules:
  - apiGroups:
      - cert-manager.io
    resources:
      - "signers"
    verbs:
      - "approve"
{{- end -}}